# Creating numpy array

In [3]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

arr2 = [20,30,40]
numpyarr = np.array(arr2)
print(numpyarr)

arr4 = np.arange(1,10,2)
print(arr4)


[1 2 3 4]
[20 30 40]
[1 3 5 7 9]


### user input numpy array

In [6]:
import numpy as np

myArray = []

size = int(input("input the size of the array:"))

for i in range(size):
    n = int(input("Enter number:"))
    myArray.append(n)
    
arr3 = np.array(myArray)
arr3
# for a in arr3:
#     print(a)




input the size of the array:4
Enter number:7
Enter number:6
Enter number:8
Enter number:9


array([7, 6, 8, 9])

In [11]:
#identity matrix
import numpy as np
arr = np.zeros([5,3],int)
arr
# print(arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
arr2 = np.eye(3)
print(arr2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
arr = np.diag([2,5,7])

print(arr)
print("Dimension:",arr.ndim)

[[2 0 0]
 [0 5 0]
 [0 0 7]]
Dimension: 2


In [14]:
import numpy as np

aa =  np.arange(0, 12).reshape(4, 3)
print(aa)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### 2D Array

In [19]:
import numpy as np

arr = np.array([[2,3,5],[4,3,2],[3,4,6],[4,8,9]])
print(arr)
print("")
print("Dimension:",arr.ndim)
print("Shape:",arr.shape)

[[2 3 5]
 [4 3 2]
 [3 4 6]
 [4 8 9]]

Dimension: 2
Shape: (4, 3)


#### Random number generation
Randint

In [45]:
import numpy as np

arr = np.random.randint(1,7,3)

print(arr)

[3 4 1]


In [23]:
arr = np.random.randint(1,5,4)
arr

array([2, 1, 3, 3])

In [48]:
arr = np.random.rand(4,2)
print(arr)
print(arr.ndim)

[[0.40726845 0.67224695]
 [0.73622037 0.82890976]
 [0.4198011  0.41310943]
 [0.27275255 0.53477826]]
2


In [49]:
arr = np.random.randn(4)
print(arr)
print(arr.ndim)

[ 0.35919145  0.09332882 -1.0018698  -1.36541286]
1
