In [3]:
import numpy as np
np.random.seed(100)
arr = np.random.randint(1,100,10)
print(arr)

arr =  np.random.rand(5)
print(arr)

arr =  np.random.randn(5)
print(arr)

[ 9 25 68 88 80 49 11 95 53 99]
[0.18646718 0.21010774 0.4527399  0.87014264 0.06368104]
[ 0.4328165   2.30447259 -0.12263538  0.01545931  0.26601635]


In [6]:
arr2d = np.random.randint(0,100,(3,3))
print(arr2d)
print("index:",arr2d[0])
print("dimension:",arr2d.ndim)

[[94 19 98]
 [63 53 27]
 [56 30 48]]
index: [94 19 98]
dimension: 2


In [9]:
arr = np.arange(25).reshape(5,5)
print(arr.ndim)
print(arr)
print(arr[2:4,1:3])

2
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[11 12]
 [16 17]]


In [10]:
print(arr.ndim)

2


In [11]:
print(arr.dtype)
print(arr.size)

int32
25


In [ ]:
a = [[2,3,4],[5,4,3],[5,4,3]]
arr = np.array(a)

print(arr)

In [12]:
a =[]

size = int(input("Enter the size:"))

for i in range(size):
    n = int(input("Enter values:"))
    a.append(n)
    
arr = np.array(a).reshape(2,2)    
print(arr)
for i in range(arr.size):
    print(arr[i])


Enter the size:4
Enter values:6
Enter values:7
Enter values:4
Enter values:8
[[6 7]
 [4 8]]
[6 7]
[4 8]


IndexError: index 2 is out of bounds for axis 0 with size 2

In [13]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


# Arithmetic Operators

In [5]:
import numpy as np
a = np.arange(4)
b = np.arange(4,8)
print(a*b)

[ 0  5 12 21]


In [14]:
a = np.random.randn(5)
b = np.arange(1,5)
#print(a)
print(np.abs(a))
print(a.max())
print(np.sqrt(64))

[0.54953168 0.58132614 0.43153324 1.01456635 0.05564646]
0.5813261439474607
8.0


In [16]:
a = np.arange(10,19).reshape(3,3)

print(a)


[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [17]:
print(a[::2])

[[10 11 12]
 [16 17 18]]


In [32]:
arr = np.arange(10,17)
print(arr)
print(arr[:7:2])


[10 11 12 13 14 15 16]
[10 12 14 16]


In [44]:
a = np.arange(10,19).reshape(3,3)

print(a)

print(a[0,:])
print(a[:,0])
print(a[0:2,0:2])


[[10 11 12]
 [13 14 15]
 [16 17 18]]
[10 11 12]
[10 13 16]
[[10 11]
 [13 14]]


In [43]:
print(a[[0,2], 0:2])

[[10 11]
 [16 17]]


# user input 2D array

In [49]:
import numpy as np

matrix = []

row = int(input("Enter row:"))
column = int(input("Enter column:"))

for i in range(row):
    a=[]
    count = 0
    for j in range(column):
        value = int(input(f"Insert {count} column value:"))
        a.append(value)
        count+=1
    matrix.append(a)
    

arr = np.array(matrix)
print(arr)


#for i in range(row):
#    for j in range(column):
#        print(matrix[i][j],end="")

    


Enter row:3
Enter column:3
Insert 0 column value:2
Insert 1 column value:3
Insert 2 column value:4
Insert 0 column value:5
Insert 1 column value:3
Insert 2 column value:1
Insert 0 column value:6
Insert 1 column value:7
Insert 2 column value:5
[[2 3 4]
 [5 3 1]
 [6 7 5]]


'\nfor i in range(row):\n    for j in range(column):\n        print(matrix[i][j],end="")\n\n'

In [58]:
arr = np.arange(12).reshape(4,3)
arr.shape = (3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [62]:
arr = np.array([10,11,12,13,14,15]) 

print(arr[0:5:2])

[10 12 14]


In [6]:
import numpy as np

arr = np.arange(0,12).reshape(4,3)

arr


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
print(arr[1:3,0:2])

[[3 4]
 [6 7]]
